# 다차원 배열의 계산
넘파이의 다차원 배열을 사용한 계산법


In [1]:
import numpy as np

In [5]:
# 다차원 배열
A = np.array([1, 2, 3, 4])
print(A)
print(np.ndim(A))
print(A.shape)
print(A.shape[0])

[1 2 3 4]
1
(4,)
4


In [6]:
B = np.array([[1,2],[3,4],[5,6]])
print(B)
print(np.ndim(B))
print(B.shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


In [8]:
# 행렬의 곱
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(f"A : {A.shape} | B : {B.shape}")
print(np.dot(A, B))

A : (2, 2) | B : (2, 2)
[[19 22]
 [43 50]]


In [24]:
A = np.array([[1,2,3],[4,5,6]])
B = np.reshape(A,(3,2))
print(A)
print(B)
print(f"A : {A.shape} | B : {B.shape}")
print(np.dot(A, B))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
A : (2, 3) | B : (3, 2)
[[22 28]
 [49 64]]


In [16]:
C = np.array([[1,2],[3,4]])
print(f"A : {A.shape} | C : {C.shape}")
print(np.dot(A,C))

A : (2, 3) | C : (2, 2)


ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [26]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([7,8])
print(f"A : {A.shape} | B : {B.shape}")
print(np.dot(A, B))

A : (3, 2) | B : (2,)
[23 53 83]


In [28]:
# 신경망에서의 행렬 곱
X = np.array([1,2])
print(X.shape)
W = np.array([[1,3,5],[2, 4, 6]])
print(W.shape)
Y = np.dot(X, W)
print(Y)

(2,)
(2, 3)
[ 5 11 17]


# 3층 신경망 구현하기
3층 신경망에서 수행되는, 입력부터 출력까지의 처리(순방향 처리)를 구현한다.