# 다차원 배열의 계산
넘파이의 다차원 배열을 사용한 계산법


In [1]:
import numpy as np

In [5]:
# 다차원 배열
A = np.array([1, 2, 3, 4])
print(A)
print(np.ndim(A))
print(A.shape)
print(A.shape[0])

[1 2 3 4]
1
(4,)
4


In [6]:
B = np.array([[1,2],[3,4],[5,6]])
print(B)
print(np.ndim(B))
print(B.shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


In [8]:
# 행렬의 곱
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(f"A : {A.shape} | B : {B.shape}")
print(np.dot(A, B))

A : (2, 2) | B : (2, 2)
[[19 22]
 [43 50]]


In [24]:
A = np.array([[1,2,3],[4,5,6]])
B = np.reshape(A,(3,2))
print(A)
print(B)
print(f"A : {A.shape} | B : {B.shape}")
print(np.dot(A, B))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
A : (2, 3) | B : (3, 2)
[[22 28]
 [49 64]]


In [16]:
C = np.array([[1,2],[3,4]])
print(f"A : {A.shape} | C : {C.shape}")
print(np.dot(A,C))

A : (2, 3) | C : (2, 2)


ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [26]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([7,8])
print(f"A : {A.shape} | B : {B.shape}")
print(np.dot(A, B))

A : (3, 2) | B : (2,)
[23 53 83]


In [28]:
# 신경망에서의 행렬 곱
X = np.array([1,2])
print(X.shape)
W = np.array([[1,3,5],[2, 4, 6]])
print(W.shape)
Y = np.dot(X, W)
print(Y)

(2,)
(2, 3)
[ 5 11 17]


# 3층 신경망 구현하기
3층 신경망에서 수행되는, 입력부터 출력까지의 처리(순방향 처리)를 구현한다.

In [30]:
# 각 층의 신호 전달 구현하기
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

print(f"W1 : {W1.shape} | X : {X.shape} | B1 : {B1.shape}")

A1 = np.dot(X,W1) + B1
print(A1)

W1 : (2, 3) | X : (2,) | B1 : (3,)
[0.3 0.7 1.1]


In [31]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

Z1 = sigmoid(A1)

print(A1)
print(Z1)

[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]


In [34]:
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.5]])
B2 = np.array([0.1, 0.2])

print(f"Z1 : {Z1.shape} | W2 : {W2.shape} | B2 : {B2.shape}")

A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)

print(A2)
print(Z2)

Z1 : (3,) | W2 : (3, 2) | B2 : (2,)
[0.51615984 1.13900095]
[0.62624937 0.75749616]


In [36]:
def identity_function(x):
    return x

W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

A3 = np.dot(Z2, W3) + B3
Y = identity_function(A3)

print(Y)

[0.31412417 0.69087328]


In [37]:
# 구현 정리
def init_network():
    # w : 가중치
    # b : 편향
    # X : 입력층 뉴런
    # z : 은닉층 뉴런
    # y : 출력층 뉴런
    network = {}
    network["W1"] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network["b1"] = np.array([0.1, 0.2, 0.3])
    network["W2"] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.5]])
    network["b2"] = np.array([0.1, 0.2])
    network["W3"] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network["b3"] = np.array([0.1, 0.2])

    return network

def forward(network, x):
    W1, W2, W3 = network["W1"], network["W2"], network["W3"]
    b1, b2, b3 = network["b1"], network["b2"], network["b3"]

    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = identity_function(a3)

    return y

network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)
print(y)


[0.31412417 0.69087328]
